# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:    
    include:
      - v*
  

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
steps:
- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    projects: 'src\Fluent.Swagger.Validation\Fluent.Swagger.Validation.csproj'
- task: DotNetCoreCLI@2
  name: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  name: 'PublishArtifact'
  displayName: 'Publish Artifact: drop'