# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:    
    include:
      - '*'
  

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/Fluent.Swagger.Validation/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    projects: 'src/Fluent.Swagger.Validation/*.csproj'
    arguments: '--configuration Release --no-restore'
- task: DotNetCoreCLI@2
  name: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/Fluent.Swagger.Validation/*.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  name: 'PublishArtifact'
  displayName: 'Publish Artifact: drop'